global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'cassandradb'
    static_configs:
      - targets: ['cassandradb:7400']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']